### PR TITLE
additional test data and sell page displays in place functionality still needs further work

### PR DESCRIPTION
**Pull request by mbntex**

### CODE REVIEW

**Review by whithang — CHANGES_REQUESTED** [review]
Michael - Do we need a username in the users table? Typically sites use the email as your username. This will affect my sign-in logic as I'm checking against email, not username.

Also, I saw you deleted some of the test data fixes I did. We need those hardcode to the unique IDs or we can't verify the data with the reference tables as it could be autofilling with other IDs.

**Review by whithang — CHANGES_REQUESTED** [review]
also, please remove or comment out lines 148 - 158 in server/index.js - you should not have the database query built here and the logic doesn't make sense. the query should be on database/index.js. and you have a callback as the query statement that doesn't have anything to return to. you also have a test function below that is immediately invoked. please only push production ready and tested code that supports your functionalities

**Comment by mbntex** [comment]
My understanding from the team conversation Friday was that there was to be  a username added. I am totally fine not having those in there. The removal of the hardcoded IDs was just me thinking I had hardcoded them by mistake for the auto-incremented id field. If that was intentionally added for testing we can definitely leave that as it is.

**Comment by mbntex** [comment]
I will get that cleaned up.

**Pull request closed without merging**
